### ISSUE TITLE
This project needs a license

### ISSUE THREAD

**Issue by emasters** [CCALI/A2JViewer#1]
Copy the A2J license from http://www.a2jauthor.org/content/a2j-author-licensing-agreement

**Comment by JessicaFrank** [comment]
I added it here -https://github.com/CCALI/A2JViewer/blob/master/LICENSE.md

**Comment by rwstaudt** [comment]
Talk to deb to make sure this licence still makes sense for a cloud based
product

**Comment by mikemitchel** [comment]
Is this still an active issue for the A2J Viewer?
