### ISSUE TITLE
Add advance nav to debug panel 

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#102]
Create a new advance navigation panel in the debug panel to be used initially by advanced or returning users. 

- [x] Should show visited pages in order
- [x] Clicking a page navigates to that page
- [x] Sync with My Progress in the Navbar
- [x] Question headings to be made in sync with My Progress  (MVP version working, issue filed for more advanced solution: #107 )
- [x] AutoScroll if list gets longer than the available space
- [x] Page link should be a combination of Step Number, Question Number and Question Text
- [x] Should resolve and live update any Macros in the Question Text
- [x] Add ellipses to prevent text overflow
- [x] Highlight the selected question or current page
- [ ] Styling for the module should be consistent with the app
- [ ] Preserve accessibility standards to match the rest of the app (Keyboard Nav, ARIA Readers)
- [ ] Write functional and component test cases for the module
- [ ] A mechanic to turn this on manually or programatically aka triggered by a set of certain stateful items
- [x] Renaming modules

**Comment by janebitovi** [comment]
shipped to production, closing
