### ISSUE TITLE
viewer mangling urls in button targets

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#105]
viewer mangling urls of button targets by setting them to lowercase which can invalidate query params and other case sensitive paths.

**Comment by janebitovi** [comment]
This sounds like it might be an important issue to address, though I haven't encountered this.

Can we get steps to reproduce/sample interview to see the problem?

Probably not difficult to fix this one

**Comment by tobiasnteireho** [comment]
appears to curently only set domain name portion to lowercase, not query params which should not affect perfomance
