### ISSUE TITLE
Update Regex for URL WCAG icon

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#111]
The regex should work according to the following conditions:

- Add span on text with decorations (underlines, bold text, italicised text ), either used individually and used together.
- Not add span with internal popup links.
- Handle null and undefined
- Work with different communication protocols (http://, https://, ftp://, news://)

**Comment by JessicaFrank** [comment]
@AnubhavDhingra can we close this ticket with the code push on 5/4/21?
