### ISSUE TITLE
Restore user progress

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#125]
- [x] User comes back to the last visited page; 
- save current page to answers file for when the user comes back
- check for restore page on interview load
- navigate to restore page if it exists
- [ ] Potential ways a user can exit an interview; Save & Exit, Browser crash, Timeout...
- [x] Should restore visited pages list and answers
- [x] Add default `A2J Restore Page` variable so author can see it in the debug panel

Happy path is to visit the last page visited, should give users an option to start over with saved answers and an option to start over from scratch.

**Comment by janebitovi** [comment]
Adv Nav history restore completed, is in production
