### ISSUE TITLE
Fill not working on default Name Page

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#127]
Sample values not populating and throwing an error 

<img width="1424" alt="Screenshot 2021-05-26 at 9 06 32 PM" src="https://user-images.githubusercontent.com/25919279/119689431-77c0d580-be66-11eb-8258-a3fdfee25691.png">

**Comment by AnubhavDhingra** [comment]
The sample values aren't saving till you refresh.

**Comment by janebitovi** [comment]
fixed in develop:
https://github.com/CCALI/a2jviewer/issues/195
