### ISSUE TITLE
TIG 20019 Advanced End User QA Feedback

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#131]
- [ ] Answer file is a mess with the new last visited page variable used by the advanced end user functionality. I was testing another issue yesterday and the anx was almost impossible to read with all the & quote things in it. I'll show an example. We need to think of a way to keep that readable. lots of authors use looking at answer files in notepad to test and debug. Especially me when dealing with LHI folks. 
[Answer file is a mess example.zip](https://github.com/CCALI/a2jviewer/files/6663992/Answer.file.is.a.mess.example.zip)

- [ ] Numbering is kind of confusing when save & exit is deleted. As a user, I'd be wondering where Q4-7 went 
![image](https://user-images.githubusercontent.com/7662028/122244867-da682880-ce8a-11eb-91dc-3897d8aef64a.png)

- [ ] Save and exit disappears, but go down path #1, then go back and change path at a fork in the road - doesn't delete those pages you saw that were different than the one path you're on now. 

- [ ] Bouncing around changes logic (ex. clear first name in 1-Question testing macros in after logic using NULL). Go forward one question where macros is used to show NULL worked.  Then go back to name question, reenter name, skip back NULL macro question & name is there. I think this is the correct behavior, but we might need to warn authors that users jumping around more can change outcomes of logic. Need to think about this a bit. 

- [x] Resume edit, then go back into preview - debug panel is open, not navigation panel even though I left with navigation panel open. May want to keep whatever option author chose as persisting through the session they're in. I could see it as annoying if I had navigation panel out and had to edit something, then had to click the nav panel check box each time I came back into preview mode. (Not super annoying, but long term if authors are bouncing back and forth between preview mode and author mode, I could see it being annoying)

**Comment by tobiasnteireho** [comment]
the answer file is probably more easily viewed in an xml viewer or editor where branches can be suppressed. Below is the view in firefox.

![a2jauthor-visitedpages](https://user-images.githubusercontent.com/23437466/122263652-5159ed00-ce9c-11eb-8964-970dc3f6c0d9.gif)

**Comment by JessicaFrank** [comment]
- [ ] Multiple questions are emboldened as the "current" question. 
![image](https://user-images.githubusercontent.com/7662028/124785211-48dd5b00-df0c-11eb-8c69-037318da42e4.png)

- [ ] Resume button doesn't turn back to Save + Exit button if on the Save and Exit question, then go back via advanced navigation panel. It does go back to S+E if you hit the "Resume" button , but at that point, you're already back on the page you hit S+E from.

**Comment by JessicaFrank** [comment]
- [ ] Macro displaying user's name does not display in advanced navigation panel. (Even after that variable is answered) 
![image](https://user-images.githubusercontent.com/7662028/137009448-5498b442-eabb-4a17-9dc1-f11c8245c7ce.png)
