### ISSUE TITLE
Restoring answers to standalone viewer 

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#132]
The flow of restoring answers from the getDataURL param is very confusing. Figure out a better way to do this.

See the following lines - https://github.com/CCALI/a2jviewer/blob/1883ca6d911d1af08d99d354676e9f2bff586f2f/src/models/interview.js#L62-L68

Is there a difference between the `answers model` and `vars`.

**Comment by janebitovi** [comment]
restore answers has been implemented in another branch and
all these old models are due for upgrades anyway... Buuuut
legacy code still dictates most of the api + model layers.
We'll address models + apis holistically when time allows.
