### ISSUE TITLE
Branching logic for Advance Nav display

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#133]
Currently the advance nav shows the list of  pages visited by a user. Ideally we would want to show a list of pages upto a uniform flow in the interview. 
If there is more than one possible destination for the user to go to from a page that would mean the list of pages can be branched at that page. 

To check for multiple destinations there are two things to look at in a `page` model: 
  - `codeAfter` key, that has a GOTO logic
  -  if there are multiple buttons on a page with different `next` target values.

The results from the `codeAfter` and `next` could be stored in an array and if there are multiple destinations in there then we branch.

**Comment by AnubhavDhingra** [comment]
@mikemitchel

**Comment by janebitovi** [comment]
![mobile-nav](https://user-images.githubusercontent.com/92131113/138724252-e81f73b5-9a1a-44c8-ac3e-fa32c8d5fa17.gif)

**Comment by janebitovi** [comment]
https://github.com/CCALI/a2jviewer/pull/159
