### ISSUE TITLE
 trigger watermark by query param

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#164]
Adding a query param that triggers watermark would be useful for testing rapid changes of interview delivery,

having the ability to enable/disable the guide watermark through a query param would also simplify the layout code on a2jorg.

related to https://github.com/CCALI/CAJA/issues/2159

**Comment by tobiasnteireho** [comment]
acually this is technically possible due to the way watermark is triggered. adding `.a2jauthor.org` anywhere in the url will show the watermark. This is probably a minor bug.

Example below on a2j.org

https://a2j.org//a2j-viewer/viewer/viewer.html?avasarala=.a2jauthor.org&autoSetDataURL=https://a2j.org/answers/interviews/1350&templateURL=../../Guides/g070kNJ5sF3azY2qbqHiKS6negMYDkw4PAQHXxJX.zip/Guide.xml&fileDataURL=../Guides/g070kNJ5sF3azY2qbqHiKS6negMYDkw4PAQHXxJX.zip&setDataURL=https://a2j.org/answers/interviews/1350&#!view/pages/page/1-Introduction

**Comment by janebitovi** [comment]
https://github.com/CCALI/a2jviewer/tree/164-watermark-qParam

**Comment by janebitovi** [comment]
&watermark=1 in the viewer url shows the watermark now
