### ISSUE TITLE
Trim audio URLs for modals/pages

### ISSUE THREAD

**Issue by mitch-mitchel** [CCALI/A2JViewer#165]
Had an issue where an Author was seeing a perma-load spinner for audio player, when the page appeared to have no audio file associated with it. That player is triggered based on a URL being present, and found in the `textAudioUrl` prop on the page in question, there was an empty space saved for the URL (`" " `) which was enough to trigger the player. 

Solution is probably to sanitize any props that can trigger an audio or video player, for example:
- page.textAudioUrl
- modalContent.audioUrl
- modalContent.videoUrl

![Screen Shot 2021-11-22 at 10 09 42 AM](https://user-images.githubusercontent.com/11528248/142897224-4d7bee7a-465a-41d9-8142-d270ed810f7c.png)

**Comment by mitch-mitchel** [comment]
the Guide that had the original error, Step6 page 5b
[KY Motion for Waiver of Costs and Fees IFP 11-17-2021 (1).zip](https://github.com/CCALI/a2jviewer/files/7582684/KY.Motion.for.Waiver.of.Costs.and.Fees.IFP.11-17-2021.1.zip)

**Comment by JessicaFrank** [comment]
Quick fix for authors experiencing issue - have them delete the space on any pages that audio player displays without an audio clip.
