### ISSUE TITLE
One ISSUE can't download from A2J author

### ISSUE THREAD

**Issue by road2one** [CCALI/A2JViewer#2]
1. Not Found error when i try to download a zip file form http://www.a2jauthor.org/app/js/author/A2J_Author.php
2. after unzipping the files - the first page is an upload button, upload doesn't work. I upload it manually to the "guides folder" and it shows as an item in the list. I clicked on it and a black page shows, no error just blank page.
   I was reading the code and looks like you guys make references files not found - on the viewer.html. there might be more errors but i just can't pass the first initial setup. If you have any solution or recent packages please reply ASAP.
   config="../package.json!npm" (not in the zip)

**Comment by JessicaFrank** [comment]
The mentioned page no longer exists. New instructions for self-hosting the A2J Viewer can be found under the Read.Me file. If you have further questions, feel free to email me Jessica@cali.org
