### ISSUE TITLE
Logo misshapen 

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jviewer#22]
Added logo for authoring organization to viewer and it's misshapen. 
![image](https://user-images.githubusercontent.com/7662028/84539306-c5294e80-acb8-11ea-8170-10ea10290288.png)

**Comment by JessicaFrank** [comment]
Currently in production 05-11-2020 version as well.

**Comment by mikemitchel** [comment]
do we have a copy of this GI/logo image being used @JessicaFrank ?

**Comment by JessicaFrank** [comment]
[My Interview (6-30-2020).zip](https://github.com/CCALI/A2JViewer/files/4853222/My.Interview.6-30-2020.zip)
@mikemitchel

**Comment by JessicaFrank** [comment]
![a2j-circle-300](https://user-images.githubusercontent.com/7662028/86152238-81f71a00-bac5-11ea-9c49-8fd60e1b973a.png)
