### ISSUE TITLE
A2J Viewer isn't running in IE11

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#238]
LHI reported that the A2J Viewer isn't running in IE11. I tested a2j.org on IE11 with Viewer version 8.1.2-2022-06-29. Nothing happens - no errors in the console, but also the viewer doesn't open/run. 

Not sure how much effort we want to put into this because IE11 is end of life as of this summer. https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

**Comment by tobiasnteireho** [comment]
won't fix. Unsupported by microsoft.
