### ISSUE TITLE
Macro isn't displaying in Step sign

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#24]
Logic to set step sign:

SET [A2J Step 2] TO "%%[Client first name TE] repeat step"

Variable name and not value displays in step signage. 
![image](https://user-images.githubusercontent.com/7662028/84541667-7500bb00-acbd-11ea-8227-b19a27f040fb.png)

**Comment by mikemitchel** [comment]
merged, closing
