### ISSUE TITLE
tests fail in firefox 108

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#241]
automated tests that were previously passing are now failing in ff 108. Passes in chrome and safari

https://github.com/CCALI/a2jviewer/actions/runs/3897567867/jobs/6655379341

**Comment by mitch-mitchel** [comment]
several tests fail in current develop branch of a2jdeps as well, going to start there - nvm, saw you filed it already @tobiasnteireho

**Comment by tobiasnteireho** [comment]
tests work in firefox 110. Even on previously failing code. https://github.com/CCALI/a2jviewer/actions/runs/4327400477
