### ISSUE TITLE
Saving errors on LHI reported

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#246]
A2J Viewer feedback from 3/22/23 
![image](https://user-images.githubusercontent.com/7662028/227555645-0f1ad557-52f6-4b1a-afc4-73f31751d903.png)

Also had reports from Claudia at LHI during monthly programmatic call that they were seeing an increase in saving errors reported by users through their Zendesk platform. No specific examples given. 

After the two above feedback forms came in, I reach out to LHI to have their technical team check their error logs around the time the feedback forms were sent to see if there was anything identifiable there. Will update this ticket with additional information received. Creating this ticket as a tracking method in case there is something we need to update on the A2J Viewer side related to this. 

Email to LHI team sent 3/24/23:

> "Hi,
> 
> We received two error reports from the same LHI user on Wednesday that came through our A2J Viewer. It appears related to the not being able to save issue that we discussed on our monthly check in call this week. 
> 
> Can you please share this with your technical team and see if they have any insight? I'll include the user's feedback form responses below. 
> 
> But here's what I think is happening based on the user's description of the problem - The user is completing a long NY guided interview (NYS Surrogate's Court Small Estate Settlement - LHI template ID 6785). Upon hitting the "Get My Document" button (that has a POST answer file server request as its destination), they are redirected from the LHI instance of the A2J Viewer to the LHI landing page that shows the save answer/assemble document/email form buttons. The user's description of hitting a page with a "bad Gateway" makes me think the page timed out on them. That type of error is usually associated with a network failure to connect. That error likely looked something like this to the user: (this is an example screenshot from a Google search. I wasn't able to replicate the user's error myself.) 
> 
> 
![image](https://user-images.githubusercontent.com/7662028/227531758-de426259-6715-4935-b41f-790a35a02e6d.png)

> 
> The feedback forms are time stamped, so it may be possible for your technical team to check your error logs and see if there were timeout errors or other issues around 7 pm CT last night. 
> 
> The error reported in the first feedback form (6:44 pm CT email time stamp) mentions the Learn More "Save and Exit explainer" not loading. I tested it in Chrome and it opened appropriately for me. That error combined with the "bad gateway" error seems to indicate some issue with the user's internet connection potentially. Perhaps a slow connection on their part is causing these timing out errors. 
> 
> image.png (Feedback form screenshots already included above in this ticket)
> 
> Please let me know if you need us to do additional research on our end."

**Comment by JessicaFrank** [comment]
Additional report of issues with saving - 3/24/23 
![image](https://user-images.githubusercontent.com/7662028/227555529-5022276d-191a-4a38-a5b5-e722303732ec.png)

**Comment by tobiasnteireho** [comment]
unsolvable
