### ISSUE TITLE
Learn Mores aren't opening in "mobile view" or "reduced user interface"

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#247]
Learn mores are appearing as clickable links in the mobile view or reduced user interface version of the A2J Viewer, but the links aren't actually clickable. 

End users aren't able to access to the content in the Learn More in any way. 

![image](https://user-images.githubusercontent.com/7662028/230440987-631956cf-9f96-4f9a-b8ee-940d03f1e455.png)

No errors in the console 

Pop ups are clickable and working as expected.

**Comment by JessicaFrank** [comment]
[Mobile view test April 2023.zip](https://github.com/CCALI/a2jviewer/files/11172674/Mobile.view.test.April.2023.zip)

https://a2j.org/guide/go/78d5f5ff-10b0-46e2-870a-7a8811708712

**Comment by tobiasnteireho** [comment]
confirmed to fail in Safari 16.3, Chrome 111, and Firefox 111 on Ventura 13.2. Only firefox displays a console error: ```Error: Promised response from onMessage listener went out of scope [init.js:79:27](moz-extension://baf7f2fa-6c58-224a-aa8b-68278b7c0c3a/background/init.js)```

**Comment by tobiasnteireho** [comment]
related to #248

**Comment by tobiasnteireho** [comment]
html differs significantly between mobile view and desktop.  This is for a learn-more in [this gi](https://a2j.org//a2j-viewer/viewer/viewer.html?templateURL=../../Guides/g070kNJ5sF3azY2qbqHiKS6negMYDkw4PAQHXxJX.zip/Guide.xml&fileDataURL=../Guides/g070kNJ5sF3azY2qbqHiKS6negMYDkw4PAQHXxJX.zip&setDataURL=https://a2j.org/answers/interviews/1350&#!view/pages/page/Q5)
Desktop view:
```
<button class="learn-more" aria-label="What does a learn more look like in mobile view?" target="_blank" on:click="../fireLearnMoreModal()" on:keydown="keydownFireClickHandler(scope.event, ../fireLearnMoreModal)" aui-action="help">What does a learn more look like in mobile view?</button>
```

mobile view:
```
<a class="learn-more" aria-label="Why does this matter?">Why does this matter?</a>
```

The mobile view is missing code to create the Modal

**Comment by JessicaFrank** [comment]
Learn Mores in reduced interface work on LHI's instance of the viewer (7.2.3, 2022-02-10 version of the viewer)

**Comment by tobiasnteireho** [comment]
@JessicaFrank try this https://viewerdev.a2jauthor.org/a2j-viewer/viewer/viewer.html?templateURL=../guides/6570d359bbf02-mobileviewtestapril2023/Guide.xml&fileDataURL=../guides/6570d359bbf02-mobileviewtestapril2023/

**Comment by JessicaFrank** [comment]
The learn more and the pop up open @tobiasnteireho in the viewerdev version, but there's still something wrong with it. At the end of the learn more (and on every page of the interview, even if no learn more associated with that page) aui-action="help" displays in that space as a hyperlink. 

![image](https://github.com/CCALI/a2jviewer/assets/7662028/e27bec1d-41a5-46c5-881e-9fdb4c4faaf7)

On the page with a learn more, it just appears at the end of the learn more link (see image above). 

On the pages with out learn mores, it is a standalone clickable link. When I click it, the learn more modal opens, but it's blank.
![image](https://github.com/CCALI/a2jviewer/assets/7662028/a7e3a5d9-bb92-43ac-b927-1852edd54541)

![image](https://github.com/CCALI/a2jviewer/assets/7662028/4b81c7c6-8812-452f-bd6d-635d10511dcc)

**Comment by tobiasnteireho** [comment]
@JessicaFrank Updated and ready for retesting.

**Comment by JessicaFrank** [comment]
@tobiasnteireho tested viewerdev on my phone and desktop. Confirmed learn mores are working as expected in reduced interface and mobile version. I tested on two GIs. Can you please test in Safari? Once that's done, I'm good locking this for a code push.

**Comment by tobiasnteireho** [comment]
works in mobile and desktop safari
