### ISSUE TITLE
Date field min/max stripping / out of dates and not restricting dates within those ranges

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#255]
Date fields are stripping out the backslash in the minimum and maximum restricting fields. 
So 10/31/2010 results in 10312010 when the author clicks out of the min or max field. 

In Preview mode, the calendar widget only displays dates within the appropriate min/max range. However, the user can manually enter an "invalid" date (outside the allotted min/max range author provided) and it'll pass to the answer field. 

Date validator in preview stills works though to convert improperly entered dates like 103100 to 10/31/2000. 

So some of the validators are working, but others are not. 

Setting the field to required/not required doesn't change impact. Tested in Chrome and Firefox with 8.1.4.0 -2022-07-06 viewer in preview and 10.1.0-2002-08-23 in author. 

Happens in newly created GIs (4-24-2023) and older GIs that have been recently updated. 

Older GIs that haven't been updated by an author clicking into that min/max field seem to work as expected. I tested with an older GI with a limit of TODAY. Worked as expected to block any manually entered dates in the future. Then went back into Author and clicked into the max field. TODAY disappeared. I can't retype it in. 

![date backslash stripped](https://user-images.githubusercontent.com/7662028/234375502-2119e475-3d47-44ee-8cbb-8d79a82de3a1.gif)

**Comment by tobiasnteireho** [comment]
slash stripping is due to this line of code https://github.com/CCALI/a2jauthor/blob/46c6c1fe58e47d1b04964f0b11a14d33cb582dd2/src/pages-tab/components/page-fields/page-fields.stache#L116 which will actually strip all non-numeric characters and collapse the remaining numerics into a string.

**Comment by JessicaFrank** [comment]
@tobiasnteireho Would the above code strip out "TODAY" as a limiter as well?

**Comment by JessicaFrank** [comment]
Can the author manually edit the JSON/xml to include the TODAY limiter and then reupload the interview to Author? They've asked about potential unintended consequences.

**Comment by tobiasnteireho** [comment]
> @tobiasnteireho Would the above code strip out "TODAY" as a limiter as well?

Yes.

> Can the author manually edit the JSON/xml to include the TODAY limiter and then reupload the interview to Author? They've asked about potential unintended consequences.

I can't think of any right now... Editing the XML and reuploading does work and this used to be supported according to some tests and https://www.a2jauthor.org/content/sample-exercise-using-functions-a2j-guided-interview but I haven't found exactly how this code was handled before.

**Comment by tobiasnteireho** [comment]
@JessicaFrank what other funtionality might have been lost due to this?

**Comment by JessicaFrank** [comment]
@tobiasnteireho Just the TODAY limiting functionality for date ranges in fields. TODAY works as a function other places (like in logic). If the code you shared above strips out any non-numbers, it's just deleting the TODAY functionality when it's inserted. It's not actually breaking anything. Interviews with TODAY in them that were created before are working in the viewer. It's just the inserting of it in Author that seems to be the issue.
