### ISSUE TITLE
Remove support for users entering unseparated mmddyy and mmddyyyy dates

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#266]
`mmddyy` and `mmddyyyy` is not a clear format and presents validation problems. Since datepicker is implemented and explicit format is specified as `mm/dd/yyyy` support for unseparated and `mmddyy` and `mmddyyyy` is unnecessary and costly to support. 

related to https://github.com/CCALI/a2jviewer/issues/256

**Comment by JessicaFrank** [comment]
the mm/dd/yyyy format is suggested, but not required for the end user. Can we enforce the format if we remove the validation?

**Comment by tobiasnteireho** [comment]
mm/dd/yyyy is enforced and required while disallowing mmddyy and mmddyyyy by #262 

fixed by #262
