### ISSUE TITLE
Destination of [Exit - Display Message] works in preview mode, but not live GIs (on a2j.org)

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/A2JViewer#268]
Destination of Exit - Display Message displays the author's message in preview mode in author, but those same interviews are showing "Missing Page [Page - nowhere doesn't exist]" errors on a2j.org

I think it was added with this issue https://github.com/CCALI/a2jauthor/issues/43

No error in the console for a2j.org interview.

**Comment by tobiasnteireho** [comment]
fixed by #278
