### ISSUE TITLE
Textlong field adds spaces

### ISSUE THREAD

**Issue by mikemitchel** [CCALI/a2jviewer#38]
If you expand a textlong field without typing anything, it adds empty spaces and a newline. If you type anything before expanding it works as expected. See attached gif for bug

![blank textlong](https://user-images.githubusercontent.com/11528248/89699191-fe61f180-d8ea-11ea-89d9-adf69526b063.gif)

**Comment by janebitovi** [comment]
doesn't seem to be an issue any more:
![longtext](https://user-images.githubusercontent.com/92131113/150177442-0f07b468-5f05-49fe-87b5-2f23e97c8066.gif)

closing
