### ISSUE TITLE
a have an interview which doesn't work properly in this version, but works fine in the a2j portal

### ISSUE THREAD

**Issue by road2one** [CCALI/A2JViewer#4]
how can i sent it over so you can have a look??

**Comment by JessicaFrank** [comment]
Hi. Feel free to email the zipped .a2j file to me at jessica@cali.org. 

I can take a look at it in our A2J viewer. 

Also, please specify what is not working in the Guided Interview. Thanks @road2one

**Comment by JessicaFrank** [comment]
Please feel free to email me jessica@cali.org if you are still experiencing this issue.
