### ISSUE TITLE
CSS: Larger field sizes and elements

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jviewer#42]
In staging v _6.0 2020-07-29_, many of the fields and other elements are 'taller' than in production v _6.0 2020-05-11_. This could result in a diminished user experience for users on smaller displays or mobile devices.

![image](https://user-images.githubusercontent.com/32527754/90073035-af82d600-dcb5-11ea-9bc3-0dc5ed59efa8.png)

Also occurs in Firefox v 78, and I assume would be the case on a mobile viewer.

**Comment by JessicaFrank** [comment]
Caused by WCAG requirement of 44 pixels for buttons and input fields.
