### ISSUE TITLE
End of interview hangs if Debug Panel is open

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jviewer#43]
When in Preview mode, if the Debug Panel is open when a button is clicked that is linked to any of the below Destinations, the page darkens and the "Author Note" dialog box shows up like normal, but the page is then frozen (the X on the dialog box is disabled, nor does clicking the page or pressing the Esc key take you back to the interview). 
- [Success - Process Form]
- [Exit - User does not qualify]
- [Exit - Save Incomplete Form]
- [Assemble - Generate PDF document]
- [Assemble - Generate PDF and Process Form]

![image](https://user-images.githubusercontent.com/32527754/90078291-a861c500-dcc1-11ea-83d2-c6139904b69f.png)

Tested in staging v _6.0 2020-07-29_ on Chrome  84.0.4147.105

Note that this does not appear to be an issue in production v _6.0 2020-05-11_.

**Comment by mikemitchel** [comment]
This is easier to reproduce if you have a learnmore modal, open debug-panel and then click the LearnMore button

**Comment by mikemitchel** [comment]
merged, closing
