### ISSUE TITLE
Calendar widget - previous and next month buttons do not work

### ISSUE THREAD

**Issue by normon66** [CCALI/a2jviewer#44]
The 'previous' and 'next' month buttons of the calendar widget do not change the active month on the calendar. This happens whether or not the field is marked as Required.
Even after a date is entered or selected, the buttons remain inactive.

![image](https://user-images.githubusercontent.com/32527754/90272833-38675200-de1b-11ea-8dc6-274b4f6b1320.png)

Test in staging v _6.0 2020-07-29_ on Chrome 84.0.4147.105 and Firefox 79.0.
Works fine in production v _6.0 2020-05-11_

**Comment by JessicaFrank** [comment]
I can't replicate this on staging v 6 2020-07-29 in Chrome Version 84.0.4147.125

![dates change](https://user-images.githubusercontent.com/7662028/90274952-1b388080-de27-11ea-8e67-e059120a6b16.gif)

Only restriction on my calendar next button is for Aug 2020 because I have TODAY as a calendar max.

**Comment by JessicaFrank** [comment]
Able to move back/next via arrows in hydra.a2jauthor.org also with version 7 2020-08-11 date on it (same Chrome browser)

**Comment by normon66** [comment]
The plot thickens. This actually goes down to the underlying html on the page. In the example I tried, I had a text field and a date field, both with the default label of just "Label". If you look at the underlying html, the ID of each of those input fields is "Label" (which seems strange to me, since the ID should be unique for every field on a given page). 

The ID can be used by javascript (such as the calendar widget) to perform certain actions or check values. I presume that because the ID was not unique, the calendar widget didn't "know" which "Label" ID to use, therefore it could not run properly.

Changing the labels of these fields so that they are different resolves the issue, but this does raise some potential concern with whatever library or utility it utilized to created the elements on the page inasmuch as the generated input IDs are not unique.

![image](https://user-images.githubusercontent.com/32527754/90279311-38b91a80-de26-11ea-8cc3-2df8d6fa39a3.png)

**Comment by JessicaFrank** [comment]
I can replicate when it's a scenario with two fields - text first, then date field. Both have label of "Label" (which is default) Calendar arrows don't work. 

However, text field + date field where text field has NO LABEL (blank) and date field has label of "Label" = calendar arrows work.

Date field + text field with date field first, then text field, both with "Label" as the label = works

Number field + date field with both "Label" = does not work. 



So looks like if date field is second and there's a field with "Label" above it and date field is also "Label" = calendar arrows don't work.

**Comment by JessicaFrank** [comment]
Also, this doesn't block an end user from entering a date into the field. Just breaks the calendar arrows. If a date is entered manually, the calendar does update to the correct month and year. 
![calendar arrows](https://user-images.githubusercontent.com/7662028/90287068-bc7e0180-de3c-11ea-99e0-73cdc14b3dc9.gif)
