### ISSUE TITLE
Add disclaimer language to Send Feedback Form

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/a2jviewer#58]
Add this language: 

This form is for feedback purposes only. There is no guarantee that it will be read or that someone will respond to you. Please do not include personal information or sensitive data. This feedback form is not an online application for services or a way to officially communicate with a legal entity. 

to this form: https://www.a2jauthor.org/A2JFeedbackForm.php?

**Comment by tobiasnteireho** [comment]
added language
