### ISSUE TITLE
Unnecessary Scroll bars

### ISSUE THREAD

**Issue by mikemitchel** [CCALI/a2jviewer#59]
as per Brett's email:

> I noticed this week that scroll bars are showing up on the edge of almost every page in A2J interviews on Chrome (v 86.0.4240.75) and Edge (v 86.0.622.43) browsers. This happens both on LHI and within a2jauthor.org.
> 
> The LHI viewer is running version 6.0-2020-05-11 and author is A2J 7.0-2020-08-31, neither of which has been updated recently, so this appears to be a shift on how those two browsers are treating html elements.
> 
> It looks like the scroll bar is showing up for the div.bubble-content -perhaps something with the calc() function used to create the max-height? 

![scrollbars](https://user-images.githubusercontent.com/11528248/96460421-cc251800-11e8-11eb-8688-dc45d5fd3b92.png)

**Comment by tobiasnteireho** [comment]
This is being reported by Florida Courts as well. This is being observed in preview mode in author. This occurs on chrome but not firefox on pages with no fields:

Chrome on windows (same behavior on mac)
![extra-scroll-chrome-windows](https://user-images.githubusercontent.com/23437466/97731972-d32f0e80-1aa3-11eb-8219-4d29956d4092.png)



Firefox on mac
![no-extra-scroll-firefox-mac](https://user-images.githubusercontent.com/23437466/97732012-e215c100-1aa3-11eb-9b26-5cf0e6e72861.png)

**Comment by tobiasnteireho** [comment]
note above images were taken on firefox 81.0.1 and MacOS 10.14.6 and Chrome v 86.0.4240.75 on win10

**Comment by tobiasnteireho** [comment]
not being observed on safari. Likely due to engine change in chrome since chrome and edge now use same rendering code.

**Comment by JessicaFrank** [comment]
Fixed with code push released on 12-16-2020; sent to LHI on 12-17-2020; pending release to A2J Author production for next code push to Author.
