### ISSUE TITLE
viewer breaks with uncaught typeError in interview

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#94]
Attached guide throws uncaught typeError on any selection, `yes` or `no`, for question `15-Q11-PetitionSec6 (M)` on Step 8. No logic in interview. Viewer crashes irrevocably.
[PROTECTION FROM ABUSE ORDER PETITION GUIDED INTERVIEW (1).zip](https://github.com/CCALI/a2jviewer/files/6125802/PROTECTION.FROM.ABUSE.ORDER.PETITION.GUIDED.INTERVIEW.1.zip)

```
Uncaught TypeError: r is undefined
    saveButtonValue https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    navigate https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    c https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    value https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    i https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    flush https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    onComplete https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    flush https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    onComplete https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    flush https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    onComplete https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    flush https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    onComplete https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    flush https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    stop https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    N https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
    f https://www.a2jauthor.org/a2jauthor/dist/bundles/a2jauthor/app.js:3
steal-sans-promises.production.js:3:719830
```

**Comment by tobiasnteireho** [comment]
demo uploaded to https://a2j.org/guide/go/3be0123f-01fe-440e-accb-18af000e8db1

**Comment by JessicaFrank** [comment]
Step 8, Question 15-Q11-PetitionSec6 (M) "NO" labelled button has a variable in it that isn't in the variables tab. So they're trying to set "false" to an unknown variable. 

Added the variable that they had typed into that field into their variables tab and I'm able to move on without the interview crashing. 

Here's the updated interview. 
[PROTECTION.FROM.ABUSE.ORDER.PETITION.GUIDED.INTERVIEW.1.zip](https://github.com/CCALI/a2jviewer/files/6125846/PROTECTION.FROM.ABUSE.ORDER.PETITION.GUIDED.INTERVIEW.1.zip)

**Comment by JessicaFrank** [comment]
Also have a page named 17.5-Q12-PetitionSec6 (L) that's being skipped. Removing the decimal in the page name seems to route question correctly.

**Comment by tobiasnteireho** [comment]
fix sent to author. Assumed resolved
